---
- hosts: localhost
  connection: local

  roles:
    - faba.useraccounts
    - faba.common

  tasks:
    # - name: "Remove pi user"
    #   user:
    #     name: pi
    #     remove: yes
    #     state: absent

    - name: "Install Packages"
      package:
        name: "{{ item }}"
        state: installed
      loop_with:
        - chromium-browser
        - xserver-xorg
        - x11-xserver-utils
        - xinit
        - openbox

    - name: "Openbox Configuration"
      blockinfile:
        path: "/etc/xdg/openbox/autostart"
        create: "yes"
        insertbefore: BOF
        block: |
          # Disable any form of screen saver / screen blanking / power management
          xset s off
          xset s noblank
          xset -dpms

          # Allow quitting the X server with CTRL-ATL-Backspace
          setxkbmap -option terminate:ctrl_alt_bksp

          # Start Chromium in kiosk mode
          sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
          sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
          chromium-browser --disable-infobars --kiosk 'https://homeassistant.fab-it.biz'

    - name: "Start X automatically on boot"
      lineinfile:
        path: "/home/pi/.bash_profile"
        line: "[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx -- -nocursor"
        insertbefore: BOF

    - name: "Configure Touchscreen"
      blockinfile:
        path: "/boot/config.txt"
        insertbefore: BOF
        block: |
          max_usb_current=1
          hdmi_force_hotplug=1 
          config_hdmi_boost=10
          hdmi_group=2 
          hdmi_mode=87 
          hdmi_cvt 1024 600 60 6 0 0 0
